name: Documentation Build

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master
    paths:
    - '.github/workflows/docbuild.yaml'
    - '**.md'
    - 'docs/**'
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          path: matter
          fetch-depth: 0
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: cache-pip
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-doc-pip
      - name: Install base dependencies
        working-directory: matter
        run: |
          sudo pip3 install -U pip
          pip3 install -r docs/requirements.txt
      - name: Build documentation
        working-directory: matter/docs
        run: |
          mkdir -p _build/src
          make html
          touch _build/html/.nojekyll
      - name: Archive cache
        if: github.repository == 'project-chip/connectedhomeip' && github.event_name == 'push' && env.GITHUB_REF_NAME == 'master'
        uses: actions/upload-artifact@v2
        with:
          name: html
          path: matter/docs/_build/html

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.repository == 'project-chip/connectedhomeip' && github.event_name == 'push' && github.ref_name == 'master'

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: html
          path: html
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DOXYGEN_DEPLOY_KEY }}
          external_repository: project-chip/connectedhomeip-doc
          publish_dir: html
          # Keep only the latest version of the documentation
          force_orphan: true
